Feature/spotimatch services
Carapuce-O-Gang/SpotiMatch.net pull request #3
Opened 2022-06-19 20:30 UTC by Fyleek

2022-06-19 23:30 UTC, CostaIsNotAvailable requested changes
Déso (c'est vraiment des trucs tout bêtes) <3

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/login.model.ts
> +export class loginData {
Première lettre en majuscule

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/register.model.ts
> +export class registerData {
Première lettre en majuscule

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/auth.model.ts
> +}
Si tout est defined (!), c'est peut être intéressant d'utiliser une interface plutôt qu'une classe

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/login.model.ts
> +}
Si tout est defined (!), c'est peut être intéressant d'utiliser une interface plutôt qu'une classe

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/register.model.ts
> +}
Si tout est defined (!), c'est peut être intéressant d'utiliser une interface plutôt qu'une classe

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/model/user.ts
> +}
Si tout est defined (!), c'est peut être intéressant d'utiliser une interface plutôt qu'une classe

2022-06-19 23:30 UTC, CostaIsNotAvailable commented on app/src/app/services/api-service/api.service.ts
> +  // }
Commentaire à supprimer

2022-06-20 19:50 UTC, Fyleek commented
🖕

2022-06-20 19:50 UTC, merged